Changed string concatenation to f-strings
CubeyTheCube/scratchclient pull request #51
Opened 2022-05-10 15:21 UTC by cryptikkUS

2022-05-10 15:38 UTC, Quantum-Codes requested changes
Just change all str conversion everywhere. 
Although I'm not sure whether cubey looks at this repo anymore or not

2022-05-10 15:38 UTC, Quantum-Codes commented on scratchclient/CloudConnection.py
> +                        f"☁ {variable}" if not variable.startswith("☁ ") else variable
This is wrong... you completely forgot about the if loop

2022-05-10 15:38 UTC, Quantum-Codes commented on scratchclient/Project.py
> +            "referer": f"https://scratch.mit.edu/projects/{str(self.id)}/",
F string autoconvert to str

2022-05-10 15:38 UTC, Quantum-Codes commented on scratchclient/Project.py
> +            f"https://api.scratch.mit.edu/users/{self.author.username}/projects/{str(self.id)}/comments/{str(comment_id)}/"
Same here

2022-05-10 21:48 UTC, cryptikkUS commented
Corrected

2022-05-31 20:43 UTC, CubeyTheCube commented
Thanks for the contribution, but I'm planning to completely refactor the code in this library so this PR wouldn't be of much use.

2022-05-31 20:43 UTC, closed without merging